full: specifikacio.tex
	pdflatex -interaction=nonstopmode -halt-on-error specifikacio.tex > output.txt
	pdflatex -interaction=nonstopmode -halt-on-error specifikacio.tex >> output.txt
	rm -f specifikacio.aux specifikacio.bbl specifikacio.blg specifikacio.out specifikacio.log specifikacio.toc specifikacio.xmpdata pdfa.xmpi tartalom/*.aux texput.log
